### ISSUE TITLE
163ページの誤り

### ISSUE THREAD

**Issue by yuyabu** [LambdaNote/errata-gosyspro-1-1#382]
シンボリックリンクの名前がsymlinkとsysmlinkで揺れています

```
// シンボリックリンク
os.Symlink("oldfile.txt", "newfile-symlink.txt")
 
// シンボリックリンクのリンク先を取得
link, err := os.ReadLink("newfile-sysmlink.txt")
```

多分タイプミスだと思いますが
シンボリックファイルの作成直後、すぐその内容を読み込むという意図のサンプルだと
修正された方が良いと思います

この表記揺れはWEB連載の頃から存在しているようです

http://ascii.jp/elem/000/001/423/1423022/

**Comment by k16shikano** [comment]
#173 に移動
